"""Generate a unit's 4diac project (library types, equipment, skills, system) from a unit specification."""
from __future__ import annotations

from pathlib import Path

from .fbxml import Project
from .library import make_library
from .spec import UnitSpec, load
from .unit import make_unit

REPO = Path(__file__).resolve().parents[1]


def generate(spec: UnitSpec, root: Path | None = None, manifest: Path | None = None) -> Project:
    """Regenerate ``4diac/<project>`` and its type manifest from ``spec``; overwrites generated files."""
    p = Project(root or REPO / "4diac" / spec.project, spec.project, spec.package,
                f"Unit {spec.unit} generated by unitgen; do not edit, regenerate")
    p.clean()
    p.write_project_files()
    p.copy_std_types()
    make_library(p)
    make_unit(p, spec)
    p.write_generic()
    p.prune()
    p.write_manifest(manifest or manifest_path(spec))
    return p


def manifest_path(spec: UnitSpec) -> Path:
    """Type manifest of a generated project (read by validate.ps1)."""
    return REPO / "4diac" / "tools" / "manifests" / f"{spec.project}.json"


__all__ = ["UnitSpec", "generate", "load", "manifest_path"]
