"""Generate 4diac projects from module specifications (``modules/*.yaml``).

Each module gets its own project (``4diac/<project>``: equipment IO, skill primitives, module
level skills, system). The module-independent types (package ``modlib``) are declared in every
project so the IDE can open it on its own, but compiled once, from the ``ModLib`` project.
"""
from __future__ import annotations

from pathlib import Path
import xml.etree.ElementTree as ET

from .fbxml import STD, Project, elem, save, wstr
from .library import LIB, make_library
from .module import make_module
from .spec import ModuleSpec, load

REPO = Path(__file__).resolve().parents[1]
LIBRARY_PROJECT = "ModLib"


def generate(spec: ModuleSpec, root: Path | None = None, manifest: Path | None = None) -> Project:
    """Regenerate ``4diac/<project>`` and its type manifest from ``spec``; overwrites generated files."""
    p = Project(root or REPO / "4diac" / spec.project, spec.project, spec.package,
                f"Module {spec.module} generated by modgen; do not edit, regenerate", external=frozenset({LIB}))
    p.clean()
    p.write_project_files()
    p.copy_std_types()
    make_library(p)
    make_module(p, spec)
    p.write_generic()
    p.prune()
    p.write_manifest(manifest or manifest_path(spec.project))
    return p


def generate_library(root: Path | None = None, manifest: Path | None = None) -> Project:
    """Regenerate ``4diac/ModLib``: the module-independent types, exported once for all modules."""
    p = Project(root or REPO / "4diac" / LIBRARY_PROJECT, LIBRARY_PROJECT, LIB,
                "Module library (modlib) generated by modgen: IO primitives, occupation, module state manager, "
                "skill state machine; do not edit, regenerate")
    p.clean()
    p.write_project_files()
    p.copy_std_types()
    make_library(p)
    p.write_generic()
    system = ET.Element("System", Name=p.name, Comment="Library only; the modules' systems use these types")
    elem(system, "Identification", Standard="61499-2")
    device = elem(system, "Device", Name="FORTE_PC", Type=STD["FORTE_PC"], x=1000, y=1000)
    elem(device, "Parameter", Name="MGR_ID", Value=wstr("localhost:61499"))
    elem(device, "Attribute", Name="Profile", Type="STRING", Value="HOLOBLOC", Comment="device profile")
    elem(device, "Attribute", Name="Color", Type="STRING", Value="255,190,111")
    elem(elem(device, "Resource", Name="RES", Type=STD["EMB_RES"], x=0, y=0), "FBNetwork")
    save(system, p.root / f"{p.name}.sys")
    p.prune()
    p.write_manifest(manifest or manifest_path(LIBRARY_PROJECT))
    return p


def manifest_path(project: str) -> Path:
    """Type manifest of a generated project (read by validate.ps1)."""
    return REPO / "4diac" / "tools" / "manifests" / f"{project}.json"


def specs() -> list[Path]:
    """All module specifications in the repository."""
    return sorted((REPO / "modules").glob("*.yaml"))


__all__ = ["ModuleSpec", "generate", "generate_library", "load", "manifest_path", "specs", "LIBRARY_PROJECT"]
