"""Generate 4diac projects from module specifications (``cell/modules/*.yaml``).

Each module gets its own project (``cell/control/<project>``: equipment IO, skill primitives,
module level skills, system). The generator's own test module is not part of the cell: its
specification and project are with this library's tests (``tests/modules``, ``tests/control``). The module-independent types (package ``modlib``) are declared in
every project so the IDE can open it on its own, but compiled once, from the ``ModLib`` project
of this library (``iec61499-skill-lib/ModLib``). Every project carries its type manifest
(``types-manifest.json``, read by ``runtime/validate.ps1``).
"""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path
import xml.etree.ElementTree as ET

from .fbxml import STD, Project, elem, save, wstr
from .library import LIB, make_library
from .module import make_module
from .spec import ModuleSpec, load

LIBRARY_ROOT = Path(__file__).resolve().parents[1]      # iec61499-skill-lib
REPO = LIBRARY_ROOT.parent
CELL = REPO / "cell"                                     # the line's modules: specs and generated control
SPECS = CELL / "modules"
PROJECTS = CELL / "control"
LIBRARY_SPECS = LIBRARY_ROOT / "tests" / "modules"         # the generator's test module (filler)
LIBRARY_PROJECTS = LIBRARY_ROOT / "tests" / "control"
LIBRARY_PROJECT = "ModLib"
MANIFEST = "types-manifest.json"


@lru_cache
def library_projects() -> frozenset[str]:
    """The projects of the generator's test modules."""
    return frozenset(load(path).project for path in library_specs())


def project_dir(project: str) -> Path:
    """Folder of a generated 4diac project: ModLib in this library, a test module with its tests,
    the modules in the cell."""
    if project == LIBRARY_PROJECT:
        return LIBRARY_ROOT / project
    return (LIBRARY_PROJECTS if project in library_projects() else PROJECTS) / project


def generate(spec: ModuleSpec, root: Path | None = None, manifest: Path | None = None) -> Project:
    """Regenerate the module's project and its type manifest from ``spec``; overwrites generated files."""
    p = Project(root or project_dir(spec.project), spec.project, spec.package,
                f"Module {spec.module} generated by modgen; do not edit, regenerate", external=frozenset({LIB}))
    p.clean()
    p.write_project_files()
    p.copy_std_types()
    make_library(p)
    make_module(p, spec)
    p.write_generic()
    p.prune()
    p.write_manifest(manifest or p.root / MANIFEST)
    return p


def generate_library(root: Path | None = None, manifest: Path | None = None) -> Project:
    """Regenerate ModLib: the module-independent types, exported once for all modules."""
    p = Project(root or project_dir(LIBRARY_PROJECT), LIBRARY_PROJECT, LIB,
                "Module library (modlib) generated by modgen: IO primitives, occupation, module state manager, "
                "skill state machine; do not edit, regenerate")
    p.clean()
    p.write_project_files()
    p.copy_std_types()
    make_library(p)
    p.write_generic()
    system = ET.Element("System", Name=p.name, Comment="Library only; the modules' systems use these types")
    elem(system, "Identification", Standard="61499-2")
    device = elem(system, "Device", Name="FORTE_PC", Type=STD["FORTE_PC"], x=1000, y=1000)
    elem(device, "Parameter", Name="MGR_ID", Comment="Device manager socket ID", Value=wstr("localhost:61499"))
    elem(device, "Attribute", Name="Profile", Type="STRING", Value="HOLOBLOC")
    elem(device, "Attribute", Name="Color", Type="STRING", Value="255,190,111")
    elem(elem(device, "Resource", Name="RES", Type=STD["EMB_RES"], x=0, y=0), "FBNetwork")
    save(system, p.root / f"{p.name}.sys")
    p.prune()
    p.write_manifest(manifest or p.root / MANIFEST)
    return p


def manifest_path(project: str) -> Path:
    """Type manifest of a generated project (read by runtime/validate.ps1)."""
    return project_dir(project) / MANIFEST


def system_file(project: str) -> Path:
    """The generated project's ``.sys``."""
    return project_dir(project) / f"{project}.sys"


def specs() -> list[Path]:
    """All module specifications of the cell."""
    return sorted(SPECS.glob("*.yaml"))


def library_specs() -> list[Path]:
    """The specifications of the generator's test modules: generated and compiled into FORTE
    like the cell's, but no module of the line."""
    return sorted(LIBRARY_SPECS.glob("*.yaml"))


def spec_file(name: str) -> Path:
    """A module's specification by its file name: the cell's, else a test module's."""
    path = SPECS / f"{name}.yaml"
    return path if path.exists() else LIBRARY_SPECS / f"{name}.yaml"


__all__ = ["ModuleSpec", "generate", "generate_library", "load", "manifest_path", "project_dir", "spec_file",
           "specs", "system_file", "library_specs", "LIBRARY_PROJECT", "SPECS", "PROJECTS", "LIBRARY_SPECS"]
